config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    resources :tasks do
      put :complete, on: :member
      put :sort, on: :collection
    end
  end

  root "projects#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/project.rb
class Project < ApplicationRecord
  validates :title, presence: true, length: {minimum: 2}

  has_many :tasks, -> { order('position ASC, created_at ASC') }, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord

  belongs_to :project
  acts_as_list scope: :project

  validates :name, presence: true
  validates :name, length: { maximum: 250 }
  # validates :completed, inclusion: { in: [true, false] }

  state_machine :initial => :pending do
    state :pending do
      validates :completed,
                inclusion: { in: [false] }
    end

    state :done do
      validates :completed,
                inclusion: { in: [true] }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # rescue_from ActiveRecord::RecordNotFound, with: :notfound
  #
  # private
  #
  # def notfound
  #   render file: 'public/404.html', status: :not_found, layout: false
  # end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[update destroy show edit]

  def index
    @project = Project.new
    @projects = Project.order(created_at: :desc).all
    @task = @project.tasks.new
  end

  def create
    @project = Project.create(title: "#{t('projects.create.title')}")
    redirect_to projects_path
  end

  def update
    @project.update(project_params)
    redirect_to projects_path
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def new
    @project = Project.new
    redirect_to projects_path
  end

  private

  def project_params
    params.require(:project).permit(:title)
  end

  def set_project
    @project = Project.find(params[:id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  protect_from_forgery except: :create
  before_action :set_project, only: %i[create update destroy complete show edit]
  before_action :set_task, only: %i[update destroy complete show edit]

  def edit
    redirect_to projects_path
  end

  def create
    @task = @project.tasks.create(task_params)
    redirect_to projects_path
  end

  def update
    @task.update(task_params)
    redirect_to projects_path
  end

  def destroy
    @task.destroy
    redirect_to projects_path
  end

  def complete
    @task.update(completed: !@task.completed)
    @task.completed? ? true : false
    @task.save
    render json: { message: "#{t('tasks.success')}" }
  end

  def sort
    @task = GlobalID::Locator.locate_signed(params[:sgid])
    @task.update(position: params[:position])
    render json: { message: "#{t('tasks.success')}" }
  end

  private

  def set_project
    @project = Project.find(params[:project_id])
  end

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>List</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/projects/_project.html.erb
<article class="project-article" data-project-id="<%= project.id %>">
  <div class="todo-header">
    <h3><%= t 'projects.create.title' %></h3>
    <ul class="todo-title-block">
      <%= form_with model: project do |form| %>
        <li class="edit-title-box"><%= form.text_field :title %></li>
        <li class="project-check-icon">
          <%= form.submit ' ' %>
        </li>
        <li class="project-edit-icon">
          <i class="fa fa-pencil project-cross-icon" aria-hidden="true"></i>
        </li>
      <% end %>
    </ul>
    <div class="project-trash-icon"><%= button_to fa_icon('trash-o'), project_path(project), method: :delete %></div>
  </div>

  <div class="todo-bar">
    <div class="todo-bar-new">
      <%= form_with model: [project, @task] do |form| %>
        <%= form.text_field :name, placeholder: "#{t('projects.task.placeholder')}" %>

        <%= form.submit "#{t('main.button_task')}", class: 'todo-bar-btn' %>
      <% end %>
    </div>
  </div>
  <div class="todo-list">
    <table>
      <tbody data-controller="drag" data-drag-url="/projects/:id/tasks/sort">
      <% unless project.tasks.empty? %>
        <%= render project.tasks, project: project %>
      <% end %>
      </tbody>
    </table>
  </div>
</article>

app/views/projects/index.html.erb
<div class="header">
  <h1><%= t 'main.title' %></h1>
</div>
<div class="content">
  <section class="list">
    <% @projects.each do |project| %>
      <div class="list-inner">
        <%= render project %>
      </div>
    <% end %>
  </section>
  <div class="new-todo">
    <%= form_with model: @project do |form| %>
      <div class="new-todo-input"><%= form.text_field :title %></div>

      <%= form.submit "#{t('main.button')}" %>
    <% end %>
  </div>
</div>



app/views/tasks/_task.html.erb
<tr data-task-id="<%= "#{task.id}" %>"
    data-sgid="<%= task.to_sgid_param %>"
    data-position="<%= task.position %>"
    class="task-box <%= task.completed? ? 'completed-task' : nil %>"
    data-controller="tasks">
  <td class="todo-list-checkbox">
    <%= check_box_tag :completed, task.completed, task.completed,
                      data: {id: task.id, controller: 'tasks', action: "tasks#complete"}, class: 'check-active'
    %>
  </td>
  <td class="todo-list-divider"></td>
  <td class="todo-list-task">
    <span class="todo-list-task-title"><%= h task.name %></span>
    <div class="edit-task-wrap">
      <%= form_with model: [project, task] do |form| %>
        <div class="edit-current-task"><%= form.text_field :name %></div>

        <%= form.submit " ", class: "edit-hide-button" %>
      <% end %>
    </div>
  </td>
  <td class="todo-list-actions">
    <ul class="hidden">
        <li>
          <a class="todo-list-task-sort" href="#">
            <i class="fa fa-sort"></i>
          </a>
        </li>
        <li class="todo-list-task-edit">
          <i class="fa fa-pencil edit-icon" aria-hidden="true"></i>
          <i class="fa fa-check check-task" aria-hidden="true"></i>
        </li>
        <li><%= button_to fa_icon('trash'), project_task_path(project, task), class: "trash-icon", method: :delete %></li>
    </ul>
  </td>
</tr>
